# Generated by Django 2.1.2 on 2018-11-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdooradventures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='clubs',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='club',
        ),
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
